import { useEffect, useState } from "react"
import { useTranslation } from "react-i18next"
import { FileVideo, FileImage, FileAudio, FileText } from "lucide-react"
import api from "../services/api"
import entvLogo from "../assets/entv-logo.png"

function Badge({ label, type }) {
  const styles = {
    FAKE: "bg-red-50 text-red-700 dark:bg-red-950/40 dark:text-red-300",
    REAL: "bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300",
    IMAGE: "bg-blue-50 text-blue-700 dark:bg-blue-950/40 dark:text-blue-300",
    VIDEO: "bg-violet-50 text-violet-700 dark:bg-violet-950/40 dark:text-violet-300",
    AUDIO: "bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300",
  }
  return (
    <span className={`inline-flex px-2 py-0.5 rounded-md text-xs font-medium ${styles[type || label] || "bg-slate-100 text-slate-600"}`}>
      {label}
    </span>
  )
}

function TypeIcon({ type }) {
  const cls = "w-3.5 h-3.5 text-slate-400 dark:text-slate-500"
  if (type === "VIDEO") return <FileVideo className={cls} />
  if (type === "IMAGE") return <FileImage className={cls} />
  return <FileAudio className={cls} />
}

function openReport(item, lang, logoSrc) {
  const translations = {
    fr: {
      title: "RAPPORT DE CONFORMITÉ",
      subtitle: "Plateforme de Détection Deepfake — ENTV",
      reportId: "ID Rapport",
      date: "Date d'analyse",
      file: "Fichier analysé",
      type: "Type de média",
      model: "Modèle utilisé",
      result: "Résultat",
      score: "Score de confiance",
      decision: "Décision finale",
      analyzedBy: "Analysé par",
      uploadedBy: "Uploadé par",
      compliant: "CONFORME",
      nonCompliant: "NON CONFORME",
      fake: "DEEPFAKE DÉTECTÉ",
      real: "CONTENU AUTHENTIQUE",
      recFake: "Ce fichier présente des caractéristiques de deepfake. Il doit être examiné manuellement avant toute diffusion ou utilisation.",
      recReal: "Ce fichier semble authentique selon l'analyse automatique. Aucune anomalie détectée.",
      signature: "Signature du responsable",
      signatureNote: "Nom et signature",
      footer: "Ce rapport a été généré automatiquement par la plateforme DeepDetect — ENTV",
      page: "Page 1/1",
    },
    en: {
      title: "COMPLIANCE REPORT",
      subtitle: "Deepfake Detection Platform — ENTV",
      reportId: "Report ID",
      date: "Analysis date",
      file: "Analyzed file",
      type: "Media type",
      model: "Model used",
      result: "Result",
      score: "Confidence score",
      decision: "Final decision",
      analyzedBy: "Analyzed by",
      uploadedBy: "Uploaded by",
      compliant: "COMPLIANT",
      nonCompliant: "NON-COMPLIANT",
      fake: "DEEPFAKE DETECTED",
      real: "AUTHENTIC CONTENT",
      recFake: "This file shows deepfake characteristics. It must be manually reviewed before any broadcast or use.",
      recReal: "This file appears authentic based on automated analysis. No anomaly detected.",
      signature: "Responsible's signature",
      signatureNote: "Name and signature",
      footer: "This report was automatically generated by the DeepDetect — ENTV platform",
      page: "Page 1/1",
    },
    ar: {
      title: "تقرير الامتثال",
      subtitle: "منصة كشف التزوير — ENTV",
      reportId: "معرف التقرير",
      date: "تاريخ التحليل",
      file: "الملف المحلل",
      type: "نوع الوسائط",
      model: "النموذج المستخدم",
      result: "النتيجة",
      score: "درجة الثقة",
      decision: "القرار النهائي",
      analyzedBy: "تم التحليل بواسطة",
      uploadedBy: "تم الرفع بواسطة",
      compliant: "مطابق",
      nonCompliant: "غير مطابق",
      fake: "تم كشف تزوير",
      real: "محتوى أصلي",
      recFake: "يُظهر هذا الملف خصائص التزوير. يجب مراجعته يدوياً قبل أي بث أو استخدام.",
      recReal: "يبدو هذا الملف أصلياً وفقاً للتحليل الآلي. لم يتم اكتشاف أي شذوذ.",
      signature: "توقيع المسؤول",
      signatureNote: "الاسم والتوقيع",
      footer: "تم إنشاء هذا التقرير تلقائياً بواسطة منصة DeepDetect — ENTV",
      page: "صفحة 1/1",
    },
  }

  const T = translations[lang] || translations.fr
  const isAr = lang === "ar"
  const dir = isAr ? "rtl" : "ltr"
  const isFake = item.label === "FAKE"
  const score = item.score ? parseFloat(item.score).toFixed(4) : "—"
  const reportId = `RPT-${item.id?.slice(0, 8).toUpperCase()}`
  const date = item.created_at ? new Date(item.created_at).toLocaleString() : "—"

  const w = window.open("", "_blank")
  w.document.write(`<!DOCTYPE html>
<html dir="${dir}" lang="${lang}">
<head>
<meta charset="UTF-8"/>
<title>${T.title}</title>
<style>
  * { margin:0; padding:0; box-sizing:border-box; }
  body {
    font-family: ${isAr ? "'Arial', 'Tahoma', sans-serif" : "'Arial', sans-serif"};
    color: #1a1a1a;
    background: #fff;
    padding: 40px;
    direction: ${dir};
  }
  .header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    border-bottom: 4px solid #CC0000;
    padding-bottom: 20px;
    margin-bottom: 24px;
  }
  .header-left { display: flex; align-items: center; gap: 16px; }
  .header-logo { height: 60px; object-fit: contain; }
  .header-title h1 { font-size: 20px; font-weight: 700; color: #CC0000; }
  .header-title p { font-size: 12px; color: #006633; margin-top: 2px; font-weight: 600; }
  .report-id { font-size: 13px; color: #555; font-weight: 600; }
  .badge {
    display: inline-block;
    padding: 6px 20px;
    border-radius: 4px;
    font-size: 15px;
    font-weight: 700;
    letter-spacing: 0.5px;
  }
  .badge-fake { background: #fef2f2; color: #b91c1c; border: 1.5px solid #fca5a5; }
  .badge-real { background: #f0fdf4; color: #15803d; border: 1.5px solid #86efac; }
  .section { margin-bottom: 20px; }
  .section-title {
    font-size: 11px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 1px;
    color: #006633;
    border-bottom: 2px solid #006633;
    padding-bottom: 4px;
    margin-bottom: 12px;
  }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }
  .field { background: #f9f9f9; border: 1px solid #e5e5e5; border-radius: 6px; padding: 10px 14px; }
  .field-label { font-size: 10px; color: #888; font-weight: 600; text-transform: uppercase; margin-bottom: 4px; }
  .field-value { font-size: 13px; font-weight: 600; color: #1a1a1a; }
  .decision-box {
    background: ${isFake ? "#fef2f2" : "#f0fdf4"};
    border: 2px solid ${isFake ? "#fca5a5" : "#86efac"};
    border-radius: 8px;
    padding: 16px 20px;
    display: flex;
    align-items: center;
    gap: 16px;
    margin-bottom: 20px;
  }
  .decision-icon { font-size: 32px; }
  .decision-label { font-size: 11px; color: #888; font-weight: 600; text-transform: uppercase; }
  .decision-value { font-size: 18px; font-weight: 800; color: ${isFake ? "#b91c1c" : "#15803d"}; }
  .rec-box {
    background: #fffbeb;
    border: 1px solid #fcd34d;
    border-radius: 6px;
    padding: 14px;
    font-size: 13px;
    line-height: 1.7;
    color: #444;
  }
  .signature-box {
    border: 1.5px dashed #ccc;
    border-radius: 8px;
    padding: 24px 20px;
    min-height: 100px;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
  }
  .signature-label { font-size: 11px; color: #888; font-weight: 600; text-transform: uppercase; margin-bottom: 8px; }
  .signature-line { border-bottom: 1px solid #aaa; margin-top: 40px; }
  .signature-note { font-size: 10px; color: #aaa; margin-top: 4px; text-align: center; }
  .footer {
    position: fixed;
    bottom: 20px;
    left: 40px;
    right: 40px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    border-top: 1px solid #e5e5e5;
    padding-top: 8px;
    font-size: 10px;
    color: #aaa;
  }
  .green-bar {
    height: 4px;
    background: linear-gradient(to right, #CC0000, #006633);
    margin-bottom: 24px;
    border-radius: 2px;
  }
  @media print {
    body { padding: 20px; }
    .footer { position: fixed; }
  }
</style>
</head>
<body>
<div class="header">
  <div class="header-left">
    <img src="${logoSrc}" class="header-logo" alt="ENTV"/>
    <div class="header-title">
      <h1>${T.title}</h1>
      <p>${T.subtitle}</p>
    </div>
  </div>
  <div class="report-id">${reportId}</div>
</div>
<div class="green-bar"></div>

<div class="section">
  <div class="section-title">${T.result} / ${T.decision}</div>
  <div class="decision-box">
    <div class="decision-icon">${isFake ? "⚠️" : "✅"}</div>
    <div>
      <div class="decision-label">${T.decision}</div>
      <div class="decision-value">${isFake ? T.fake : T.real}</div>
    </div>
    <div style="margin-${isAr ? "right" : "left"}:auto">
      <span class="badge ${isFake ? "badge-fake" : "badge-real"}">${isFake ? T.nonCompliant : T.compliant}</span>
    </div>
  </div>
</div>

<div class="section">
  <div class="section-title">${T.file} / ${T.type}</div>
  <div class="grid">
    <div class="field"><div class="field-label">${T.reportId}</div><div class="field-value">${reportId}</div></div>
    <div class="field"><div class="field-label">${T.date}</div><div class="field-value">${date}</div></div>
    <div class="field"><div class="field-label">${T.file}</div><div class="field-value">${item.original_name || "—"}</div></div>
    <div class="field"><div class="field-label">${T.type}</div><div class="field-value">${item.media_type || "—"}</div></div>
    <div class="field"><div class="field-label">${T.score}</div><div class="field-value">${score}</div></div>
    <div class="field"><div class="field-label">${T.model}</div><div class="field-value">${item.model_name || "—"}</div></div>
    <div class="field"><div class="field-label">${T.uploadedBy}</div><div class="field-value">${item.uploaded_by || "—"}</div></div>
    <div class="field"><div class="field-label">${T.analyzedBy}</div><div class="field-value">${item.analyzed_by || "—"}</div></div>
  </div>
</div>

<div class="section">
  <div class="section-title">Recommandation</div>
  <div class="rec-box">${isFake ? T.recFake : T.recReal}</div>
</div>

<div class="section">
  <div class="section-title">${T.signature}</div>
  <div class="signature-box">
    <div class="signature-label">${T.signature}</div>
    <div class="signature-line"></div>
    <div class="signature-note">${T.signatureNote}</div>
  </div>
</div>

<div class="footer">
  <span>${T.footer}</span>
  <span>${T.page}</span>
</div>

<script>window.onload = function() { window.print(); }</script>
</body>
</html>`)
  w.document.close()
}

export default function HistoryPage() {
  const { t, i18n } = useTranslation()
  const [history, setHistory] = useState([])
  const [loading, setLoading] = useState(true)
  const [activeFilter, setActiveFilter] = useState("all")
  const [reportLang, setReportLang] = useState("fr")

  useEffect(() => {
    api.get("/analysis/history")
      .then((res) => setHistory(Array.isArray(res.data) ? res.data : []))
      .catch(() => setHistory([]))
      .finally(() => setLoading(false))
  }, [])

  // Charger le logo en base64 pour l'inclure dans le PDF
  const [logoBase64, setLogoBase64] = useState("")
  useEffect(() => {
    fetch("/src/assets/entv-logo.png")
      .then(r => r.blob())
      .then(blob => {
        const reader = new FileReader()
        reader.onload = () => setLogoBase64(reader.result)
        reader.readAsDataURL(blob)
      })
      .catch(() => setLogoBase64(""))
  }, [])

  const filters = [
    { key: "all", label: t("filterAll") },
    { key: "FAKE", label: t("filterFake") },
    { key: "REAL", label: t("filterReal") },
    { key: "IMAGE", label: t("filterImages") },
    { key: "VIDEO", label: t("filterVideos") },
    { key: "AUDIO", label: t("filterAudios") },
  ]

  const filtered = history.filter((h) => {
    if (activeFilter === "all") return true
    if (["FAKE", "REAL"].includes(activeFilter)) return h.label === activeFilter
    return h.media_type === activeFilter
  })

  return (
    <div className="max-w-6xl mx-auto">
      <div className="mb-5">
        <h1 className="text-xl font-medium">{t("historyTitle")}</h1>
        <p className="text-sm text-slate-500 dark:text-slate-400 mt-0.5">{t("historySub")}</p>
      </div>

      {/* Filters + langue rapport */}
      <div className="flex flex-wrap gap-2 mb-4 items-center justify-between">
        <div className="flex gap-2 flex-wrap">
          {filters.map(({ key, label }) => (
            <button
              key={key}
              onClick={() => setActiveFilter(key)}
              className={`px-3.5 py-1.5 rounded-xl text-sm transition ${
                activeFilter === key
                  ? "bg-red-50 dark:bg-red-950/40 text-red-700 dark:text-red-300 border border-red-200 dark:border-red-800"
                  : "border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800"
              }`}
            >
              {label}
            </button>
          ))}
        </div>
        <div className="flex items-center gap-2">
          <span className="text-xs text-slate-500">Langue rapport :</span>
          {["fr", "en", "ar"].map((l) => (
            <button
              key={l}
              onClick={() => setReportLang(l)}
              className={`px-3 py-1 rounded-lg text-xs font-medium transition border ${
                reportLang === l
                  ? "bg-green-700 text-white border-green-700"
                  : "border-slate-300 dark:border-slate-600 text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800"
              }`}
            >
              {l.toUpperCase()}
            </button>
          ))}
        </div>
      </div>

      {/* Table */}
      <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 overflow-hidden">
        <div className="grid grid-cols-[2fr_1fr_1.2fr_1fr_1fr_auto] text-xs font-medium text-slate-400 dark:text-slate-500 px-4 py-3 border-b border-slate-100 dark:border-slate-800 bg-slate-50 dark:bg-slate-800/50 uppercase tracking-wide">
          <div>{t("colFile")}</div>
          <div>{t("colType")}</div>
          <div>{t("colDate")}</div>
          <div>{t("colResult")}</div>
          <div>{t("colScore")}</div>
          <div>Rapport</div>
        </div>

        {loading ? (
          <div className="flex items-center justify-center py-16">
            <div className="w-6 h-6 border-2 border-red-500 border-t-transparent rounded-full animate-spin" />
          </div>
        ) : filtered.length === 0 ? (
          <div className="py-16 text-center text-sm text-slate-400 dark:text-slate-500">
            {t("noHistory")}
          </div>
        ) : (
          filtered.map((item, i) => (
            <div
              key={i}
              className="grid grid-cols-[2fr_1fr_1.2fr_1fr_1fr_auto] px-4 py-3.5 border-b border-slate-100 dark:border-slate-800 last:border-0 items-center hover:bg-slate-50 dark:hover:bg-slate-800/50 transition"
            >
              <div className="flex items-center gap-2 min-w-0">
                <div className="w-7 h-7 rounded-lg bg-slate-100 dark:bg-slate-800 flex items-center justify-center flex-shrink-0">
                  <TypeIcon type={item.media_type} />
                </div>
                <span className="text-sm truncate">{item.original_name || item.media_file_id || "—"}</span>
              </div>
              <div><Badge label={item.media_type || "?"} type={item.media_type} /></div>
              <div className="text-sm text-slate-500 dark:text-slate-400">
                {item.created_at ? new Date(item.created_at).toLocaleString() : "—"}
              </div>
              <div><Badge label={item.label || "?"} type={item.label} /></div>
              <div className="text-sm text-slate-600 dark:text-slate-300 font-mono">
                {item.score ? parseFloat(item.score).toFixed(4) : "—"}
              </div>
              <div>
                <button
                  onClick={() => openReport(item, reportLang, logoBase64)}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-red-600 hover:bg-red-700 text-white text-xs font-medium transition"
                >
                  <FileText size={11} />
                  PDF
                </button>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  )
}