import { useEffect, useMemo, useRef, useState } from "react"
import { useTranslation } from "react-i18next"
import { useAuth } from "../context/AuthContext"
import {
  UploadCloud, FileVideo, FileImage, FileAudio,
  Trash2, Play, RotateCcw, CheckCircle2, AlertCircle,
  ArrowRight, ShieldCheck,
} from "lucide-react"
import api from "../services/api"

function getMediaType(file) {
  if (file.type.startsWith("video")) return "VIDEO"
  if (file.type.startsWith("image")) return "IMAGE"
  if (file.type.startsWith("audio")) return "AUDIO"
  return null
}

function MediaIcon({ type, size = 16 }) {
  const cls = `text-slate-500 dark:text-slate-400`
  if (type === "VIDEO") return <FileVideo size={size} className={cls} />
  if (type === "IMAGE") return <FileImage size={size} className={cls} />
  return <FileAudio size={size} className={cls} />
}

function Badge({ label }) {
  const styles = {
    FAKE: "bg-red-50 text-red-700 dark:bg-red-950/40 dark:text-red-300",
    REAL: "bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300",
    "NON-COMPLIANT": "bg-red-50 text-red-700 dark:bg-red-950/40 dark:text-red-300",
    COMPLIANT: "bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300",
    IMAGE: "bg-blue-50 text-blue-700 dark:bg-blue-950/40 dark:text-blue-300",
    VIDEO: "bg-red-50 text-red-700 dark:bg-red-950/40 dark:text-red-300",
    AUDIO: "bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300",
  }
  return (
    <span className={`inline-flex px-2 py-0.5 rounded-md text-xs font-medium ${styles[label] || "bg-slate-100 text-slate-600"}`}>
      {label}
    </span>
  )
}

function openReport(item, lang, logoSrc) {
  const translations = {
    fr: {
      title: "RAPPORT DE CONFORMITÉ",
      subtitle: "Plateforme de Détection Deepfake — ENTV",
      reportId: "ID Rapport", date: "Date d'analyse", file: "Fichier analysé",
      type: "Type de média", model: "Modèle utilisé", result: "Résultat",
      score: "Score de confiance", decision: "Décision finale",
      analyzedBy: "Analysé par", uploadedBy: "Uploadé par",
      compliant: "CONFORME", nonCompliant: "NON CONFORME",
      fake: "DEEPFAKE DÉTECTÉ", real: "CONTENU AUTHENTIQUE",
      recFake: "Ce fichier présente des caractéristiques de deepfake. Il doit être examiné manuellement avant toute diffusion ou utilisation.",
      recReal: "Ce fichier semble authentique selon l'analyse automatique. Aucune anomalie détectée.",
      signature: "Signature du responsable", signatureNote: "Nom et signature",
      footer: "Ce rapport a été généré automatiquement par la plateforme DeepDetect — ENTV",
      page: "Page 1/1",
    },
    en: {
      title: "COMPLIANCE REPORT",
      subtitle: "Deepfake Detection Platform — ENTV",
      reportId: "Report ID", date: "Analysis date", file: "Analyzed file",
      type: "Media type", model: "Model used", result: "Result",
      score: "Confidence score", decision: "Final decision",
      analyzedBy: "Analyzed by", uploadedBy: "Uploaded by",
      compliant: "COMPLIANT", nonCompliant: "NON-COMPLIANT",
      fake: "DEEPFAKE DETECTED", real: "AUTHENTIC CONTENT",
      recFake: "This file shows deepfake characteristics. It must be manually reviewed before any broadcast or use.",
      recReal: "This file appears authentic based on automated analysis. No anomaly detected.",
      signature: "Responsible's signature", signatureNote: "Name and signature",
      footer: "This report was automatically generated by the DeepDetect — ENTV platform",
      page: "Page 1/1",
    },
    ar: {
      title: "تقرير الامتثال",
      subtitle: "منصة كشف التزوير — ENTV",
      reportId: "معرف التقرير", date: "تاريخ التحليل", file: "الملف المحلل",
      type: "نوع الوسائط", model: "النموذج المستخدم", result: "النتيجة",
      score: "درجة الثقة", decision: "القرار النهائي",
      analyzedBy: "تم التحليل بواسطة", uploadedBy: "تم الرفع بواسطة",
      compliant: "مطابق", nonCompliant: "غير مطابق",
      fake: "تم كشف تزوير", real: "محتوى أصلي",
      recFake: "يُظهر هذا الملف خصائص التزوير. يجب مراجعته يدوياً قبل أي بث أو استخدام.",
      recReal: "يبدو هذا الملف أصلياً وفقاً للتحليل الآلي. لم يتم اكتشاف أي شذوذ.",
      signature: "توقيع المسؤول", signatureNote: "الاسم والتوقيع",
      footer: "تم إنشاء هذا التقرير تلقائياً بواسطة منصة DeepDetect — ENTV",
      page: "صفحة 1/1",
    },
  }

  const T = translations[lang] || translations.fr
  const isAr = lang === "ar"
  const dir = isAr ? "rtl" : "ltr"
  const isFake = item.label === "FAKE"
  const score = item.score ? parseFloat(item.score).toFixed(4) : "—"
  const reportId = `RPT-${(item.id || Date.now().toString()).slice(0, 8).toUpperCase()}`
  const date = item.created_at ? new Date(item.created_at).toLocaleString() : "—"

  const w = window.open("", "_blank")
  w.document.write(`<!DOCTYPE html>
<html dir="${dir}" lang="${lang}">
<head>
<meta charset="UTF-8"/>
<title>${T.title}</title>
<style>
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family: ${isAr ? "'Arial', 'Tahoma', sans-serif" : "'Arial', sans-serif"}; color: #1a1a1a; background: #fff; padding: 40px; direction: ${dir}; }
  .header { display: flex; align-items: center; justify-content: space-between; border-bottom: 4px solid #CC0000; padding-bottom: 20px; margin-bottom: 24px; }
  .header-left { display: flex; align-items: center; gap: 16px; }
  .header-logo { height: 60px; object-fit: contain; }
  .header-title h1 { font-size: 20px; font-weight: 700; color: #CC0000; }
  .header-title p { font-size: 12px; color: #006633; margin-top: 2px; font-weight: 600; }
  .report-id { font-size: 13px; color: #555; font-weight: 600; }
  .badge { display: inline-block; padding: 6px 20px; border-radius: 4px; font-size: 15px; font-weight: 700; letter-spacing: 0.5px; }
  .badge-fake { background: #fef2f2; color: #b91c1c; border: 1.5px solid #fca5a5; }
  .badge-real { background: #f0fdf4; color: #15803d; border: 1.5px solid #86efac; }
  .section { margin-bottom: 20px; }
  .section-title { font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; color: #006633; border-bottom: 2px solid #006633; padding-bottom: 4px; margin-bottom: 12px; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }
  .field { background: #f9f9f9; border: 1px solid #e5e5e5; border-radius: 6px; padding: 10px 14px; }
  .field-label { font-size: 10px; color: #888; font-weight: 600; text-transform: uppercase; margin-bottom: 4px; }
  .field-value { font-size: 13px; font-weight: 600; color: #1a1a1a; }
  .decision-box { background: ${isFake ? "#fef2f2" : "#f0fdf4"}; border: 2px solid ${isFake ? "#fca5a5" : "#86efac"}; border-radius: 8px; padding: 16px 20px; display: flex; align-items: center; gap: 16px; margin-bottom: 20px; }
  .decision-icon { font-size: 32px; }
  .decision-label { font-size: 11px; color: #888; font-weight: 600; text-transform: uppercase; }
  .decision-value { font-size: 18px; font-weight: 800; color: ${isFake ? "#b91c1c" : "#15803d"}; }
  .rec-box { background: #fffbeb; border: 1px solid #fcd34d; border-radius: 6px; padding: 14px; font-size: 13px; line-height: 1.7; color: #444; }
  .signature-box { border: 1.5px dashed #ccc; border-radius: 8px; padding: 24px 20px; min-height: 100px; display: flex; flex-direction: column; justify-content: space-between; }
  .signature-label { font-size: 11px; color: #888; font-weight: 600; text-transform: uppercase; margin-bottom: 8px; }
  .signature-line { border-bottom: 1px solid #aaa; margin-top: 40px; }
  .signature-note { font-size: 10px; color: #aaa; margin-top: 4px; text-align: center; }
  .footer { position: fixed; bottom: 20px; left: 40px; right: 40px; display: flex; justify-content: space-between; align-items: center; border-top: 1px solid #e5e5e5; padding-top: 8px; font-size: 10px; color: #aaa; }
  .green-bar { height: 4px; background: linear-gradient(to right, #CC0000, #006633); margin-bottom: 24px; border-radius: 2px; }
  @media print { body { padding: 20px; } .footer { position: fixed; } }
</style>
</head>
<body>
<div class="header">
  <div class="header-left">
    <img src="${logoSrc}" class="header-logo" alt="ENTV"/>
    <div class="header-title"><h1>${T.title}</h1><p>${T.subtitle}</p></div>
  </div>
  <div class="report-id">${reportId}</div>
</div>
<div class="green-bar"></div>

<div class="section">
  <div class="section-title">${T.result} / ${T.decision}</div>
  <div class="decision-box">
    <div class="decision-icon">${isFake ? "⚠️" : "✅"}</div>
    <div>
      <div class="decision-label">${T.decision}</div>
      <div class="decision-value">${isFake ? T.fake : T.real}</div>
    </div>
    <div style="margin-${isAr ? "right" : "left"}:auto">
      <span class="badge ${isFake ? "badge-fake" : "badge-real"}">${isFake ? T.nonCompliant : T.compliant}</span>
    </div>
  </div>
</div>

<div class="section">
  <div class="section-title">${T.file} / ${T.type}</div>
  <div class="grid">
    <div class="field"><div class="field-label">${T.reportId}</div><div class="field-value">${reportId}</div></div>
    <div class="field"><div class="field-label">${T.date}</div><div class="field-value">${date}</div></div>
    <div class="field"><div class="field-label">${T.file}</div><div class="field-value">${item.original_name || "—"}</div></div>
    <div class="field"><div class="field-label">${T.type}</div><div class="field-value">${item.media_type || "—"}</div></div>
    <div class="field"><div class="field-label">${T.score}</div><div class="field-value">${score}</div></div>
    <div class="field"><div class="field-label">${T.model}</div><div class="field-value">${item.model_name || "—"}</div></div>
    <div class="field"><div class="field-label">${T.uploadedBy}</div><div class="field-value">${item.uploaded_by || "—"}</div></div>
    <div class="field"><div class="field-label">${T.analyzedBy}</div><div class="field-value">${item.analyzed_by || "—"}</div></div>
  </div>
</div>

<div class="section">
  <div class="section-title">Recommandation</div>
  <div class="rec-box">${isFake ? T.recFake : T.recReal}</div>
</div>

<div class="section">
  <div class="section-title">${T.signature}</div>
  <div class="signature-box">
    <div class="signature-label">${T.signature}</div>
    <div class="signature-line"></div>
    <div class="signature-note">${T.signatureNote}</div>
  </div>
</div>

<div class="footer">
  <span>${T.footer}</span>
  <span>${T.page}</span>
</div>
<script>window.onload = function() { window.print(); }</script>
</body>
</html>`)
  w.document.close()
}

export default function UploadPage() {
  const { t } = useTranslation()
  const { user } = useAuth()
  const inputRef = useRef(null)
  const [reportLang, setReportLang] = useState("fr")
  const [logoBase64, setLogoBase64] = useState("")

  const [queue, setQueue] = useState(() => {
    try {
      const saved = localStorage.getItem("upload_queue")
      if (!saved) return []
      return JSON.parse(saved).map((item) => ({ ...item, file: null }))
    } catch {
      return []
    }
  })

  const [analysisItem, setAnalysisItem] = useState(null)
  const [draggingItem, setDraggingItem] = useState(null)
  const [dragOverUpload, setDragOverUpload] = useState(false)
  const [dragOverAnalyze, setDragOverAnalyze] = useState(false)
  const [zoneMsg, setZoneMsg] = useState(null)

  useEffect(() => {
    const toSave = queue.map(({ file, ...rest }) => rest)
    localStorage.setItem("upload_queue", JSON.stringify(toSave))
  }, [queue])

  useEffect(() => {
    fetch("/src/assets/entv-logo.png")
      .then(r => r.blob())
      .then(blob => {
        const reader = new FileReader()
        reader.onload = () => setLogoBase64(reader.result)
        reader.readAsDataURL(blob)
      })
      .catch(() => setLogoBase64(""))
  }, [])

  const readyCount = useMemo(() => queue.filter((i) => i.progress === 100).length, [queue])

  function showMsg(text, type = "warning") {
    setZoneMsg({ text, type })
    setTimeout(() => setZoneMsg(null), 3500)
  }

  async function handleFiles(files) {
    const valid = Array.from(files).filter((f) => getMediaType(f))
    if (!valid.length) return showMsg("Seuls images, vidéos et audios sont acceptés.")

    const items = valid.map((f, i) => ({
      id: `${f.name}-${f.size}-${Date.now()}-${i}`,
      file: f,
      name: f.name,
      mediaType: getMediaType(f),
      size: (f.size / 1024 / 1024).toFixed(2),
      progress: 0,
      status: "uploading",
      mediaId: null,
    }))

    setQueue((prev) => [...prev, ...items])

    for (const item of items) {
      try {
        const formData = new FormData()
        formData.append("file", item.file)
        const res = await api.post("/media/upload", formData, {
          headers: { "Content-Type": "multipart/form-data" },
          onUploadProgress: (e) => {
            const pct = Math.round((e.loaded * 100) / (e.total || 1))
            setQueue((prev) => prev.map((q) =>
              q.id === item.id ? { ...q, progress: Math.min(pct, 99) } : q
            ))
          },
        })
        const mediaId = res.data?.id
        setQueue((prev) => prev.map((q) =>
          q.id === item.id ? { ...q, progress: 100, status: "uploaded", mediaId } : q
        ))
      } catch (_) {
        setQueue((prev) => prev.map((q) =>
          q.id === item.id ? { ...q, progress: 0, status: "error" } : q
        ))
        showMsg(`Erreur upload: ${item.name}`)
      }
    }
  }

  function handleDragStart(item) {
    if (item.progress < 100) return showMsg(t("waitUpload"))
    setDraggingItem(item)
  }

  function handleDropToAnalyze(e) {
    e.preventDefault()
    setDragOverAnalyze(false)
    if (!draggingItem) return
    if (analysisItem && analysisItem.analysisStatus === "analyzing") {
      showMsg(t("oneFileOnly"))
      setDraggingItem(null)
      return
    }
    setQueue((prev) => prev.filter((i) => i.id !== draggingItem.id))
    setAnalysisItem({ ...draggingItem, analysisStatus: "pending", analysisProgress: 0, result: null, reportData: null })
    setDraggingItem(null)
  }

  function returnToQueue() {
    if (!analysisItem) return
    setQueue((prev) => [{ ...analysisItem, analysisStatus: "idle", analysisProgress: 0, result: null, reportData: null }, ...prev])
    setAnalysisItem(null)
  }

  async function startRealAnalysis() {
    if (!analysisItem) return
    try {
      setZoneMsg(null)
      setAnalysisItem((prev) => ({ ...prev, analysisStatus: "analyzing", analysisProgress: 10, result: null, reportData: null }))

      let mediaId = analysisItem.mediaId

      if (!mediaId) {
        if (!analysisItem.file) {
          showMsg("Fichier non disponible, veuillez le re-uploader.")
          setAnalysisItem((prev) => ({ ...prev, analysisStatus: "pending", analysisProgress: 0 }))
          return
        }
        const formData = new FormData()
        formData.append("file", analysisItem.file)
        const uploadRes = await api.post("/media/upload", formData, {
          headers: { "Content-Type": "multipart/form-data" },
          onUploadProgress: (e) => {
            const pct = Math.round((e.loaded * 100) / (e.total || 1))
            setAnalysisItem((prev) => ({ ...prev, analysisProgress: Math.min(pct, 60) }))
          },
        })
        mediaId = uploadRes.data?.id || uploadRes.data?.media_id
      }

      if (!mediaId) throw new Error("media_id introuvable")

      setAnalysisItem((prev) => ({ ...prev, analysisProgress: 75 }))

      const analysisRes = await api.post(`/analysis/${mediaId}/run`)
      const data = analysisRes.data?.result || analysisRes.data

      const label = data?.label || "UNKNOWN"
      const score = data?.score ?? data?.prob_fake ?? data?.video_analysis?.prob_fake ?? 0
      const scoreStr = typeof score === "number" ? score.toFixed(4) : String(score)

      setAnalysisItem((prev) => ({
        ...prev,
        analysisStatus: "done",
        analysisProgress: 100,
        result: { label, score: scoreStr },
        // ✅ Données pour openReport avec uploaded_by et analyzed_by
        reportData: {
          id: mediaId,
          label,
          score: scoreStr,
          original_name: analysisItem.name,
          media_type: analysisItem.mediaType,
          model_name: data?.model_name || "N/A",
          uploaded_by: user?.full_name || "—",
          analyzed_by: user?.full_name || "—",
          created_at: new Date().toISOString(),
        },
      }))

    } catch (err) {
      setAnalysisItem((prev) => ({ ...prev, analysisStatus: "pending", analysisProgress: 0 }))
      showMsg(err?.response?.data?.detail || err.message || t("errorAnalysis"))
    }
  }

  return (
    <div className="max-w-7xl mx-auto">
      <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-3 mb-5">
        <div>
          <h1 className="text-xl font-medium">{t("wsTitle")}</h1>
          <p className="text-sm text-slate-500 dark:text-slate-400 mt-0.5">{t("wsSub")}</p>
        </div>
        <div className="flex gap-2">
          <div className="text-sm px-4 py-2 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900">
            <span className="text-slate-500 dark:text-slate-400">{t("queueLabel")} </span>
            <strong>{queue.length}</strong>
          </div>
          <div className="text-sm px-4 py-2 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900">
            <span className="text-slate-500 dark:text-slate-400">{t("readyLabel")} </span>
            <strong>{readyCount}</strong>
          </div>
        </div>
      </div>

      {zoneMsg && (
        <div className={`mb-4 flex items-center gap-2 px-4 py-3 rounded-xl text-sm border ${
          zoneMsg.type === "success"
            ? "bg-emerald-50 dark:bg-emerald-950/30 border-emerald-200 dark:border-emerald-900 text-emerald-700 dark:text-emerald-300"
            : "bg-amber-50 dark:bg-amber-950/30 border-amber-200 dark:border-amber-900 text-amber-700 dark:text-amber-300"
        }`}>
          <AlertCircle size={14} className="flex-shrink-0" />
          {zoneMsg.text}
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-[300px_1fr] gap-4" style={{ minHeight: "600px" }}>

        {/* LEFT: UPLOAD QUEUE */}
        <div
          onDragOver={(e) => { e.preventDefault(); setDragOverUpload(true) }}
          onDragLeave={() => setDragOverUpload(false)}
          onDrop={(e) => { e.preventDefault(); setDragOverUpload(false); handleFiles(e.dataTransfer.files) }}
          className={`flex flex-col gap-3 bg-white dark:bg-slate-900 rounded-2xl border p-4 transition ${
            dragOverUpload ? "border-red-400 dark:border-red-600" : "border-slate-200 dark:border-slate-800"
          }`}
        >
          <div className="flex items-center justify-between">
            <div>
              <div className="text-sm font-medium">{t("uploadQueueLabel")}</div>
              <div className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">{t("dropFormats")}</div>
            </div>
            <span className="text-xs px-2 py-0.5 rounded-full bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300">
              {queue.length}
            </span>
          </div>

          <button
            onClick={() => inputRef.current?.click()}
            className="flex items-center justify-center gap-2 w-full py-2.5 rounded-xl bg-red-600 hover:bg-red-700 text-white text-sm font-medium transition"
          >
            <UploadCloud size={16} />
            {t("uploadBtn")}
          </button>

          <input
            ref={inputRef}
            type="file"
            accept="image/*,video/*,audio/*"
            multiple
            className="hidden"
            onChange={(e) => { handleFiles(e.target.files); e.target.value = "" }}
          />

          <div className="flex-1 overflow-y-auto space-y-2 min-h-0">
            {queue.length === 0 ? (
              <div className="h-full min-h-40 flex flex-col items-center justify-center border border-dashed border-slate-200 dark:border-slate-700 rounded-xl text-slate-400 dark:text-slate-500 gap-2">
                <UploadCloud size={28} />
                <span className="text-sm">{t("dropMsg")}</span>
              </div>
            ) : (
              queue.map((item) => (
                <div
                  key={item.id}
                  draggable={item.progress === 100}
                  onDragStart={() => handleDragStart(item)}
                  className={`rounded-xl border p-3 transition ${
                    item.progress === 100
                      ? "cursor-grab border-slate-200 dark:border-slate-700 hover:border-slate-300 dark:hover:border-slate-600 bg-slate-50 dark:bg-slate-800"
                      : item.status === "error"
                      ? "cursor-not-allowed border-red-200 dark:border-red-900 bg-red-50/50 dark:bg-red-950/10"
                      : "cursor-not-allowed border-slate-100 dark:border-slate-800 bg-slate-50/70 dark:bg-slate-800/50 opacity-70"
                  }`}
                >
                  <div className="flex items-start gap-2.5">
                    <div className="w-8 h-8 rounded-lg bg-slate-100 dark:bg-slate-700 flex items-center justify-center flex-shrink-0">
                      <MediaIcon type={item.mediaType} />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="text-sm font-medium truncate">{item.name}</div>
                      <div className="text-xs text-slate-400 dark:text-slate-500 mt-0.5">
                        {item.mediaType} · {item.size} MB
                      </div>
                    </div>
                    <button
                      onClick={() => setQueue((prev) => prev.filter((i) => i.id !== item.id))}
                      className="text-slate-300 dark:text-slate-600 hover:text-red-500 transition flex-shrink-0"
                    >
                      <Trash2 size={14} />
                    </button>
                  </div>

                  {item.status === "error" ? (
                    <div className="mt-2 flex items-center gap-1.5 text-xs text-red-500">
                      <AlertCircle size={12} />
                      Erreur upload
                    </div>
                  ) : item.progress < 100 ? (
                    <div className="mt-2.5">
                      <div className="flex justify-between text-xs text-slate-400 dark:text-slate-500 mb-1">
                        <span>{t("uploading")}</span>
                        <span>{item.progress}%</span>
                      </div>
                      <div className="h-1.5 bg-slate-100 dark:bg-slate-700 rounded-full overflow-hidden">
                        <div className="h-full bg-red-500 rounded-full transition-all" style={{ width: `${item.progress}%` }} />
                      </div>
                    </div>
                  ) : (
                    <div className="mt-2 flex items-center gap-1.5 text-xs text-emerald-600 dark:text-emerald-400">
                      <CheckCircle2 size={12} />
                      {t("uploadedOk")}
                    </div>
                  )}
                </div>
              ))
            )}
          </div>
        </div>

        {/* RIGHT: ANALYSIS ZONE */}
        <div
          onDragOver={(e) => { e.preventDefault(); setDragOverAnalyze(true) }}
          onDragLeave={() => setDragOverAnalyze(false)}
          onDrop={handleDropToAnalyze}
          className={`flex flex-col bg-white dark:bg-slate-900 rounded-2xl border-2 border-dashed transition ${
            dragOverAnalyze
              ? "border-red-400 dark:border-red-600 bg-red-50/30 dark:bg-red-950/10"
              : analysisItem
              ? "border-slate-200 dark:border-slate-800 border-solid"
              : "border-slate-200 dark:border-slate-700"
          }`}
        >
          <div className="px-5 py-4 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between flex-shrink-0">
            <div>
              <div className="text-sm font-medium">{t("analysisZone")}</div>
              <div className="text-xs text-slate-400 dark:text-slate-500 mt-0.5">{t("oneFile")}</div>
            </div>
            {analysisItem && (
              <span className="text-xs px-2.5 py-0.5 rounded-full bg-red-50 dark:bg-red-950/40 text-red-700 dark:text-red-300">
                Actif
              </span>
            )}
          </div>

          <div className="flex-1 overflow-y-auto">
            {!analysisItem ? (
              <div className="h-full min-h-80 flex flex-col items-center justify-center gap-4 p-8 text-center">
                <div className="w-14 h-14 rounded-2xl bg-slate-100 dark:bg-slate-800 flex items-center justify-center">
                  <ArrowRight size={28} className="text-slate-400 dark:text-slate-500" />
                </div>
                <div>
                  <div className="text-lg font-medium">{t("dropHere")}</div>
                  <div className="text-sm text-slate-500 dark:text-slate-400 mt-1 max-w-sm">{t("dropSub")}</div>
                </div>
              </div>
            ) : (
              <div className="p-5 space-y-4">
                <div className="bg-slate-50 dark:bg-slate-800 rounded-2xl p-4">
                  <div className="flex items-start gap-3">
                    <div className="w-10 h-10 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 flex items-center justify-center flex-shrink-0">
                      <MediaIcon type={analysisItem.mediaType} size={18} />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="font-medium truncate">{analysisItem.name}</div>
                      <div className="text-sm text-slate-500 dark:text-slate-400 mt-0.5">
                        {analysisItem.mediaType} · {analysisItem.size} MB
                      </div>
                    </div>
                    <button
                      onClick={() => setAnalysisItem(null)}
                      className="text-slate-300 dark:text-slate-600 hover:text-red-500 transition"
                    >
                      <Trash2 size={16} />
                    </button>
                  </div>

                  {analysisItem.analysisStatus !== "done" && (
                    <div className="flex gap-2 mt-4 flex-wrap">
                      <button
                        onClick={startRealAnalysis}
                        disabled={analysisItem.analysisStatus === "analyzing"}
                        className="flex items-center gap-2 px-4 py-2 rounded-xl bg-red-600 hover:bg-red-700 text-white text-sm font-medium transition disabled:opacity-50 disabled:cursor-not-allowed"
                      >
                        <Play size={14} />
                        {analysisItem.analysisStatus === "analyzing" ? t("analyzing") : t("analyzeBtnText")}
                      </button>
                      <button
                        onClick={returnToQueue}
                        className="flex items-center gap-2 px-4 py-2 rounded-xl border border-slate-200 dark:border-slate-700 text-sm hover:bg-slate-100 dark:hover:bg-slate-700 transition"
                      >
                        <RotateCcw size={14} />
                        {t("returnUpload")}
                      </button>
                    </div>
                  )}

                  {analysisItem.analysisStatus === "analyzing" && (
                    <div className="mt-4">
                      <div className="flex justify-between text-xs text-slate-500 dark:text-slate-400 mb-1.5">
                        <span>{t("analysisProgress")}</span>
                        <span>{analysisItem.analysisProgress || 0}%</span>
                      </div>
                      <div className="h-2 bg-slate-200 dark:bg-slate-700 rounded-full overflow-hidden">
                        <div
                          className="h-full bg-red-500 rounded-full transition-all duration-300"
                          style={{ width: `${analysisItem.analysisProgress || 0}%` }}
                        />
                      </div>
                    </div>
                  )}
                </div>

                {/* RAPPORT */}
                {analysisItem.analysisStatus === "done" && analysisItem.result && analysisItem.reportData && (
                  <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5">
                    <div className="flex items-center gap-3 mb-5">
                      <div className="w-9 h-9 rounded-xl bg-red-50 dark:bg-red-950/40 flex items-center justify-center">
                        <ShieldCheck size={18} className="text-red-600 dark:text-red-400" />
                      </div>
                      <div>
                        <div className="font-medium">{t("reportTitle")}</div>
                        <div className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">{t("reportGenAfter")}</div>
                      </div>
                    </div>

                    <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 mb-4">
                      {[
                        { label: t("generatedAt"), value: new Date().toLocaleString() },
                        { label: t("mediaType"), value: analysisItem.mediaType },
                        { label: t("analysisLabel"), value: <Badge label={analysisItem.result.label} /> },
                        { label: t("finalDecision"), value: <Badge label={analysisItem.result.label === "REAL" ? t("COMPLIANT") : t("NON-COMPLIANT")} /> },
                        { label: t("confidenceScore"), value: analysisItem.result.score },
                        { label: "Modèle", value: analysisItem.reportData.model_name },
                      ].map(({ label, value }, i) => (
                        <div key={i} className="bg-slate-50 dark:bg-slate-800 rounded-xl p-3">
                          <div className="text-xs text-slate-400 dark:text-slate-500 mb-1.5">{label}</div>
                          <div className="text-sm font-medium">{value}</div>
                        </div>
                      ))}
                    </div>

                    {/* uploaded_by / analyzed_by */}
                    <div className="grid grid-cols-2 gap-3 mb-4">
                      <div className="bg-slate-50 dark:bg-slate-800 rounded-xl p-3">
                        <div className="text-xs text-slate-400 dark:text-slate-500 mb-1.5">Uploadé par</div>
                        <div className="text-sm font-medium">{analysisItem.reportData.uploaded_by}</div>
                      </div>
                      <div className="bg-slate-50 dark:bg-slate-800 rounded-xl p-3">
                        <div className="text-xs text-slate-400 dark:text-slate-500 mb-1.5">Analysé par</div>
                        <div className="text-sm font-medium">{analysisItem.reportData.analyzed_by}</div>
                      </div>
                    </div>

                    <div className="bg-slate-50 dark:bg-slate-800 rounded-xl p-3 mb-4">
                      <div className="text-xs text-slate-400 dark:text-slate-500 mb-1.5">{t("recommendation")}</div>
                      <div className="text-sm leading-relaxed">
                        {analysisItem.result.label === "REAL" ? t("recReal") : t("recFake")}
                      </div>
                    </div>

                    {/* Sélecteur langue */}
                    <div className="flex items-center gap-2 mb-3 flex-wrap">
                      <span className="text-xs text-slate-500">Langue rapport :</span>
                      {["fr", "en", "ar"].map((l) => (
                        <button
                          key={l}
                          onClick={() => setReportLang(l)}
                          className={`px-3 py-1 rounded-lg text-xs font-medium transition border ${
                            reportLang === l
                              ? "bg-green-700 text-white border-green-700"
                              : "border-slate-300 dark:border-slate-600 text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800"
                          }`}
                        >
                          {l.toUpperCase()}
                        </button>
                      ))}
                    </div>

                    <div className="flex gap-2 flex-wrap">
                      <button
                        onClick={() => openReport(analysisItem.reportData, reportLang, logoBase64)}
                        className="flex items-center gap-2 px-4 py-2 rounded-xl bg-red-600 hover:bg-red-700 text-white text-sm font-medium transition"
                      >
                        🖨 {t("print")}
                      </button>
                      <button
                        onClick={() => setAnalysisItem(null)}
                        className="flex items-center gap-2 px-4 py-2 rounded-xl border border-slate-200 dark:border-slate-700 text-sm hover:bg-slate-50 dark:hover:bg-slate-800 transition"
                      >
                        <RotateCcw size={14} />
                        Analyser un autre fichier
                      </button>
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
